package CalApp;


/**
* CalApp/calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Thursday, 23 March, 2023 2:26:47 PM IST
*/

public interface calculator extends calculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calculator
